name: 'Octobay Rewards'
description: 'Automate crypto payments to your contributors.'
inputs:
  to-address:
    desciption: 'The Ethereum address of the receiving user. (Can be retrieved using octobay/get-user-config-action.)'
    required: true
  from-address:
    desciption: 'The Ethereum address to send the rewards from. Defaults to the first address derived from the provided seed phrase.'
    required: false
  seed-phrase:
    desciption: 'The seed phrase for the wallet that pays contributors.'
    required: true
  rpc-node:
    description: 'An ethereum RPC node.'
    required: false
    default: 'https://mainnet.rpc.fiews.io/v1/free'
outputs:
  tx:
    description: 'The Ethereum transaction receipt.'
runs:
  using: 'node12'
  main: 'dist/index.js'
